name: Use GitHub Secrets

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use secret in a script
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        run: |
          echo "Using the secret in a script:"
          echo "MY_SECRET is $MY_SECRET"

      - name: Use secret as an environment variable
        run: echo "MY_SECRET is set"
        env:
          MY_SECRET: ${{ secrets.MY_SECRET }}
        shell: bash